language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
# Command to run tests
script:
  - pytest tests
  - pytest --cov=./ --cov-report=xml
  - codecov
