- name: 'gcr.io/cloud-builders/gcloud'
  args:
  — functions
  — deploy
  — runtime=python37
  — trigger-http
  — entry-point=main # Function entry point
  — Preprocessor_Auto_Deployed # Function name
waitFor: ['_']
id: 'deploying-a-serverless-function'
